version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27017:27017

  eventms:
    build: "./Event MS/"
    ports:
      - 50051:50051
    depends_on:
      - db
      - mongo
