# Generated by Django 4.2.3 on 2023-07-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_power_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='power',
            old_name='usuario',
            new_name='villano',
        ),
    ]
