# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api_proto/client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61pi_proto/client.proto\x12\tapi_proto\x1a\x1bgoogle/protobuf/empty.proto\"\x19\n\x07Villain\x12\x0e\n\x06nombre\x18\x01 \x01(\t\"\x14\n\x12VillainListRequest\"$\n\x16VillainRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xb8\x02\n\x11VillainController\x12=\n\x04List\x12\x1d.api_proto.VillainListRequest\x1a\x12.api_proto.Villain\"\x00\x30\x01\x12\x32\n\x06\x43reate\x12\x12.api_proto.Villain\x1a\x12.api_proto.Villain\"\x00\x12\x43\n\x08Retrieve\x12!.api_proto.VillainRetrieveRequest\x1a\x12.api_proto.Villain\"\x00\x12\x32\n\x06Update\x12\x12.api_proto.Villain\x1a\x12.api_proto.Villain\"\x00\x12\x37\n\x07\x44\x65stroy\x12\x12.api_proto.Villain\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_proto.client_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_VILLAIN']._serialized_start=66
  _globals['_VILLAIN']._serialized_end=91
  _globals['_VILLAINLISTREQUEST']._serialized_start=93
  _globals['_VILLAINLISTREQUEST']._serialized_end=113
  _globals['_VILLAINRETRIEVEREQUEST']._serialized_start=115
  _globals['_VILLAINRETRIEVEREQUEST']._serialized_end=151
  _globals['_VILLAINCONTROLLER']._serialized_start=154
  _globals['_VILLAINCONTROLLER']._serialized_end=466
# @@protoc_insertion_point(module_scope)
