# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api_proto/villain.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61pi_proto/villain.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"[\n\x0eVillainRequest\x12\x16\n\x0enombre_villano\x18\x01 \x01(\t\x12\x31\n\rfecha_ingreso\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\"\n\x0fVillainResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2C\n\x0eVillainService\x12\x31\n\nAddVillain\x12\x0f.VillainRequest\x1a\x10.VillainResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_proto.villain_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_VILLAINREQUEST']._serialized_start=60
  _globals['_VILLAINREQUEST']._serialized_end=151
  _globals['_VILLAINRESPONSE']._serialized_start=153
  _globals['_VILLAINRESPONSE']._serialized_end=187
  _globals['_VILLAINSERVICE']._serialized_start=189
  _globals['_VILLAINSERVICE']._serialized_end=256
# @@protoc_insertion_point(module_scope)
